language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.3
      env: dependencies=lowest

before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then travis_retry composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest; fi;
  - composer show -i

script:
  - phpunit --coverage-text

notifications:
    email: false
